/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: "index",
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Blocks',
      collapsible: true,
      collapsed: true,
      items: [
        'blocks/barrel', 'blocks/crucible', 'blocks/sieve', 'blocks/miscellaneous'
      ],
    },
    {
      type: 'category',
      label: 'Items',
      collapsible: true,
      collapsed: true,
      items: [
        'items/crooks', 'items/dolls', 'items/hammers', 'items/miscellaneous'
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        'configuration/configuration', 'configuration/crafttweaker', 'configuration/data_pack', 'configuration/kubejs'
      ],
    },
    {
      type: 'doc',
      id: "contributing",
    },
    {
      type: 'html',
      value: `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4549739881111156"
                    crossorigin="anonymous" ></script>
              <ins class="adsbygoogle"
                    style="display:block"
                    data-ad-client="ca-pub-4549739881111156"
                    data-ad-slot="9508544881"
                    data-ad-format="auto"
                    data-full-width-responsive="true"></ins>
              <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
              </script>`
    }
  ],

};

module.exports = sidebars;
